/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/lib/theme.ts
 * Command: astryx theme build src/lib/theme.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

/// <reference path="./academic-navy.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const academicNavyTheme: DefinedTheme;
