/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/lib/theme.ts
 * Command: astryx theme build src/lib/theme.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface HeadingTypeMap {
    'display-1': true;
    'display-2': true;
    'display-3': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/Avatar' {
  interface AvatarStatusDotVariantMap {
    'success': true;
    'error': true;
  }
}
