/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as RpsIdRouteImport } from './routes/rps/$id'
import { Route as RpsBaruRouteImport } from './routes/rps/baru'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RpsIdRoute = RpsIdRouteImport.update({
  id: '/rps/$id',
  path: '/rps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RpsBaruRoute = RpsBaruRouteImport.update({
  id: '/rps/baru',
  path: '/rps/baru',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/rps/$id': typeof RpsIdRoute
  '/rps/baru': typeof RpsBaruRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/rps/$id': typeof RpsIdRoute
  '/rps/baru': typeof RpsBaruRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/rps/$id': typeof RpsIdRoute
  '/rps/baru': typeof RpsBaruRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/settings' | '/admin/login' | '/rps/$id' | '/rps/baru' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/admin/login' | '/rps/$id' | '/rps/baru' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/admin/login'
    | '/rps/$id'
    | '/rps/baru'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  RpsIdRoute: typeof RpsIdRoute
  RpsBaruRoute: typeof RpsBaruRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rps/$id': {
      id: '/rps/$id'
      path: '/rps/$id'
      fullPath: '/rps/$id'
      preLoaderRoute: typeof RpsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rps/baru': {
      id: '/rps/baru'
      path: '/rps/baru'
      fullPath: '/rps/baru'
      preLoaderRoute: typeof RpsBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  RpsIdRoute: RpsIdRoute,
  RpsBaruRoute: RpsBaruRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
